const MAP_TYPE_TIMELINE = 'Timeline'
const MAP_TYPE_2D_GRID = '2DGrid'

const TIMECODE_FORMAT = 'HH:mm:ss:SSS'

const SESSION_DISTANCE_SECONDS = 6 * 60 * 60

export default {
  MAP_TYPE_TIMELINE,
  MAP_TYPE_2D_GRID,
  TIMECODE_FORMAT,
  SESSION_DISTANCE_SECONDS
}
