sudo: false

language: node_js
node_js: "10.16.0"

before_install:
  - cd app

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-mosys.git src/components/mosys
  - git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-shared.git src/components/shared
  - npm install
  - npm rebuild

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: Build macOS & Windows
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Build Linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm run release

addons:
  ssh_known_hosts: gitlab.rlp.net
