sudo: false

language: node_js
node_js: "10.16.0"

git:
  submodules: false

install:
  - git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-mosys.git src/components/mosys
  - git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-shared.git src/components/shared
  - npm install
  - ln -s /usr/local/opt/openssl/include/openssl /usr/local/include/
  - npm run rebuild

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Build macOS & Windows
      os: osx
      osx_image: xcode10.1
      script:
        - NODE_ENV=production npx quasar build -m electron -t mat -v 4.2.5 --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Build Linux
      os: linux
      dist: trusty
      script:
        - NODE_ENV=productionnpx quasar build -m electron -t mat -v 4.2.5

addons:
  ssh_known_hosts: gitlab.rlp.net
