aliases:
  - &pull-submodules
    name: Pull Submodules
    command: |
      ssh-keyscan gitlab.rlp.net >> ~/.ssh/known_hosts
      git submodule init
      git submodule update
  - &install-dependencies
    name: Install dependencies
    command: |
      apk add --update --no-cache nodejs nodejs-npm python make g++ pkgconfig libsecret-dev
      npm config set unsafe-perm true
      npm i -g npm
      node --version
      npm --version
      npm i -g @quasar/cli
      npm install

version: 2
jobs:
  release_dev:
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Dev Image
          environment:
            IS_STAGING: true
            API_HOST: https://api-dev.motionbank.org
          command: |
            set +o pipefail
            AUTH0_CLIENT_ID=${DEV_AUTH0_CLIENT_ID} npm run build-dev
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:dev .
            docker push motionbank/systems-frontend:dev

  release_production:
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          environment:
            API_HOST: https://api.motionbank.org
            MIGRATION_PREVIOUS_URL: https://legacy.motionbank.org
            MIGRATION_PREVIOUS_INFO_URL: https://medium.com/motion-bank/supporting-dance-practice-and-education-during-covid-19-ca43e71eb93
          command: |
            set +o pipefail
            AUTH0_CLIENT_ID=${PROD_AUTH0_CLIENT_ID} npm run build
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:${CIRCLE_BRANCH} .
            docker push motionbank/systems-frontend:${CIRCLE_BRANCH}

  release_legacy:
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            AUTH0_CLIENT_ID=${PROD_AUTH0_CLIENT_ID} npm run build
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:${CIRCLE_BRANCH} .
            docker push motionbank/systems-frontend:${CIRCLE_BRANCH}

  release_staging:
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Staging Image
          environment:
            BUILD_NAME_EXT: staging
            API_HOST: https://api-staging.motionbank.org
          command: |
            set +o pipefail
            AUTH0_CLIENT_ID=${STAGING_AUTH0_CLIENT_ID} npm run build
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:staging .
            docker push motionbank/systems-frontend:staging

workflows:
  version: 2
  build_pipeline:
    jobs:
      - release_dev:
          filters:
            branches:
              only: master
      - release_staging:
          filters:
            branches:
              only: staging
      - release_legacy:
          filters:
            branches:
              only: /^release_1_.+$/
      - release_production:
          filters:
            branches:
              only: /^release_2_.+$/

