version: 2
jobs:
  build_dev:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            ssh-keyscan gitlab.rlp.net >> ~/.ssh/known_hosts
            git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-mosys.git src/components/mosys
            git clone https://gitlab.rlp.net/motionbank/mbjs/quasar-components-shared.git src/components/shared
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache nodejs nodejs-npm python make g++ pkgconfig libsecret-dev
            npm config set unsafe-perm true
            npm i -g npm
            node --version
            npm --version
            npm i -g @quasar/cli
      - run:
          name: Build Dev Image
          environment:
            AUTH0_REDIRECT_URL: https://dev.motionbank.org
            UI_HOST: https://dev.motionbank.org
            IS_STAGING: true
            API_HOST: https://api-dev.motionbank.org
          command: |
            set +o pipefail
            npm install
            AUTH0_CLIENT_ID=${DEV_AUTH0_CLIENT_ID} SENTRY_DSN=${DEV_SENTRY_DSN} npm run build
            docker build --no-cache -t motionbank/systems-frontend:dev .
      - run:
          name: Push Docker Image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push motionbank/systems-frontend:dev

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build_dev:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_dev
